#!/usr/bin/env bash
# One-time local dev setup: Postgres DB, Python venv, schema bootstrap, frontend deps.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="${OPENESTIMATE_DATA_DIR:-$ROOT/.local-data}"
VENV="${ROOT}/.venv"

echo "==> OpenConstructionERP local setup (root: $ROOT)"

mkdir -p "$DATA_DIR/vectors" "$DATA_DIR/uploads" "$DATA_DIR/qdrant_cwicr"

if ! pg_isready -h localhost -p 5432 -q 2>/dev/null; then
  echo "ERROR: PostgreSQL is not accepting connections on localhost:5432."
  echo "       Start Postgres (e.g. brew services start postgresql@18) and re-run."
  exit 1
fi

echo "==> Ensuring PostgreSQL role/database (oe / openestimate)"
psql -h localhost -p 5432 -d postgres -v ON_ERROR_STOP=1 <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'oe') THEN
    CREATE ROLE oe WITH LOGIN PASSWORD 'oe' CREATEDB;
  END IF;
END $$;
SELECT 'CREATE DATABASE openestimate OWNER oe'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'openestimate')\gexec
GRANT ALL PRIVILEGES ON DATABASE openestimate TO oe;
SQL
psql -h localhost -p 5432 -d openestimate -v ON_ERROR_STOP=1 -c \
  "GRANT ALL ON SCHEMA public TO oe; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO oe;"

cat >"$ROOT/backend/.env" <<ENV
# Generated by scripts/setup-local.sh — edit as needed
APP_ENV=development
APP_DEBUG=true
LOG_LEVEL=INFO
ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000

DATABASE_URL=postgresql+asyncpg://oe:oe@localhost:5432/openestimate
DATABASE_SYNC_URL=postgresql://oe:oe@localhost:5432/openestimate

STORAGE_BACKEND=local
JWT_SECRET=ibs-local-dev-jwt-secret-min-32-chars!!

DEMO_USER_PASSWORD=DemoPass1234!
DEMO_ESTIMATOR_PASSWORD=DemoPass1234!
DEMO_MANAGER_PASSWORD=DemoPass1234!

OE_REGISTRATION_MODE=open

# CivilCore local dev: hide AI nav in sidebar (routes remain; set false for full ERP UX)
CIVILCORE_DEMO=true

VECTOR_BACKEND=lancedb
VECTOR_DATA_DIR=${DATA_DIR}/vectors
CWICR_QDRANT_PATH=${DATA_DIR}/qdrant_cwicr
ENV

# Vite reads repo-root .env (see frontend/vite.config.ts envDir)
ROOT_ENV="$ROOT/.env"
touch "$ROOT_ENV"
grep -q '^VITE_CIVILCORE_DEMO=' "$ROOT_ENV" 2>/dev/null || echo 'VITE_CIVILCORE_DEMO=true' >>"$ROOT_ENV"
grep -q '^VITE_APP_NAME=' "$ROOT_ENV" 2>/dev/null || echo 'VITE_APP_NAME=CivilCore' >>"$ROOT_ENV"

if [[ ! -d "$VENV" ]]; then
  echo "==> Creating Python venv ($VENV)"
  python3 -m venv "$VENV"
fi
# shellcheck source=/dev/null
source "$VENV/bin/activate"
pip install -U pip wheel

echo "==> Building frontend (required for editable backend install)"
(cd "$ROOT/frontend" && npm ci)
(cd "$ROOT/frontend" && npm run build)

echo "==> Installing backend (editable) with server + vector extras"
pip install -e "$ROOT/backend[server,vector]"

if [[ "${INSTALL_SEMANTIC:-0}" == "1" ]]; then
  echo "==> Installing semantic extras (~large download)"
  pip install -e "$ROOT/backend[semantic]"
fi

echo "==> Bootstrapping PostgreSQL schema (create_all + demo seed on first API start)"
BOOT_PORT=8010
set -a
# shellcheck disable=SC1090
source "$ROOT/backend/.env"
set +a
(cd "$ROOT/backend" && uvicorn app.main:create_app --factory --host 127.0.0.1 --port "$BOOT_PORT") &
BOOT_PID=$!
for _ in $(seq 1 90); do
  if curl -sf "http://127.0.0.1:${BOOT_PORT}/api/health" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
if ! curl -sf "http://127.0.0.1:${BOOT_PORT}/api/health" >/dev/null 2>&1; then
  kill "$BOOT_PID" 2>/dev/null || true
  echo "ERROR: Backend did not become healthy on port $BOOT_PORT"
  exit 1
fi
kill "$BOOT_PID" 2>/dev/null || true
wait "$BOOT_PID" 2>/dev/null || true

echo ""
echo "Setup complete."
echo "  Data dir:     $DATA_DIR"
echo "  Backend env:  $ROOT/backend/.env"
echo "  Start dev:    $ROOT/scripts/run-dev.sh"
echo ""
echo "Demo login: demo@openestimator.io / DemoPass1234!"
echo "Optional: INSTALL_SEMANTIC=1 $0  — adds sentence-transformers / FlagEmbedding"
